name = "CauseOfActions"
uuid = "2dac9a18-3094-11e9-267d-0deede91c9b6"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
Callbacks = "5c501fca-fc9b-11e8-1fb9-dbe118bb7e64"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MCTS = "e12ccd36-dcad-5f33-8774-9175229e7b33"
Omega = "f05e9b56-6544-11e8-2dc8-1fe18f3ca5da"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Spec = "526a04b8-654b-11e8-1588-db2a414f95b5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
