name = "IslandDispute"
uuid = "45712444-4191-11e9-29cf-e36a0a2b952b"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
Callbacks = "db1e321a-d383-57b4-a664-0144fd54e973"
DiscreteValueIteration = "4b033969-44f6-5439-a48b-c11fa3648068"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MCTS = "e12ccd36-dcad-5f33-8774-9175229e7b33"
Omega = "1af16e33-887a-59b3-8344-18f1671b3ade"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Spec = "b8ccf107-3a88-5e0f-823b-b838c6a0f327"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
