name = "InvRayTrace"
uuid = "8a45d79e-a589-11e8-1025-51d29e337d7e"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
Callbacks = "db1e321a-d383-57b4-a664-0144fd54e973"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Omega = "1af16e33-887a-59b3-8344-18f1671b3ade"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RayTrace = "9441d024-97fe-11e8-2154-4d1b79854d30"
Spec = "b8ccf107-3a88-5e0f-823b-b838c6a0f327"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tensorboard = "0b0dfcba-97db-11e8-112a-b5f40c7258d9"
