name = "WolvesAndRabbits"
uuid = "f2c9b6be-3cab-11e9-126f-9f8a39aec30f"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
Callbacks = "db1e321a-d383-57b4-a664-0144fd54e973"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Omega = "1af16e33-887a-59b3-8344-18f1671b3ade"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Spec = "b8ccf107-3a88-5e0f-823b-b838c6a0f327"
